### ISSUE TITLE
Provide types for TypeScript

### ISSUE THREAD

**Issue by usernamehw** [egoist/vue-slim-tabs#25]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24100%20Funded-%2300A156.svg" />](https://issuehunt.io/r/egoist/vue-slim-tabs/issues/25)

`*.ts`
```ts
import * as Tabs from 'vue-slim-tabs';
```
> Could not find a declaration file for module 'vue-slim-tabs'. '.../node_modules/vue-slim-tabs/dist/vue-slim-tabs.common.js' implicitly has an 'any' type. Try `npm install @types/vue-slim-tabs` if it exists or add a new declaration (.d.ts) file containing `declare module 'vue-slim-tabs';`ts(7016)

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $100.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($100.00)
### Submitted pull Requests
- [#27 Add TS typings](https://issuehunt.io/r/egoist/vue-slim-tabs/pull/27)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/egoist/vue-slim-tabs/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by egoist** [comment]
PR welcome.
